#version 420 core
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable
#extension GL_ARB_compute_variable_group_size : enable

layout(std140, binding = 0) buffer Positions {
    vec3 positions[];
};

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint gid = gl_GlobalInvocationID.x;	// The .y and .z are both 1 in this case.
    vec3 p = positions[gid];
}
